
      dist: xenial
      language: python
      virtualenv:
        system_site_packages: true
      python: 
        - "3.7"
        - "3.7-dev"
      before_script:
        - cd backend/talkcraft/test
      install:
        - pip install django
        - pip install djangorestframework
        - pip install djangorestframework-jwt 
        - pip install django-cors-headers
        - pip install pytest-django
      script:
        - pytest

      language: node_js
      node_js:
        - v6
      before_script:
        - cd frontend
      script:
        - npm test -- --coverage && npm test
      sudo:
        false
      cache:
        yarn
      after_success:
        - bash <(curl -ss https://codecov.io/bash)
