sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
  - '3.5'
install:
  - pip install django
  - pip install djangorestframework
  - pip install djangorestframework-jwt
  - pip install django-cors-headers
before_script: cd backend/talkcraft
script: 
  - bash init.sh 
after_script: cd ~
